API_BASE_URL = "http://localhost:3000"
DEFAULT_TIMEOUT_SECONDS = 15
WINDOW_TITLE = "YELP Application"
MAIN_WINDOW_WIDTH = 1280
MAIN_WINDOW_HEIGHT = 720
SUB_WINDOW_WIDTH = 1050
SUB_WINDOW_HEIGHT = 700
